name: chipseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bamtools=2.5.2
  - bcftools=1.17
  - bedtools=2.31.0
  - bioconductor-diffbind=3.8.0
  - bwa=0.7.17
  - fastqc=0.12.1
  - idr=2.0.4.2
  - igvtools=2.14.1
  - homer=4.11
  - macs2=2.2.7.1
  - phantompeakqualtools=1.2.2
  - samtools=1.17
  - sra-tools=3.0.5
  - trimmomatic=0.39
  - ucsc-gtftogenepred=477
  - ucsc-genepredtobed=477
